before_deploy:
- git config --local user.name "Mushware Machine"
- git config --local user.email "machine@mushware.com"
deploy:
  edge: true
  file: adanaxis*.zip
  file_glob: true
  provider: releases
  on:
    tags: true
  overwrite: false
  prerelease: true
  repo: mushware/adanaxis-win64deps
  token:
    secure: uw9WK2QH6ZbTwdV5sFAcqMqxFpp4ZlutGi5zkCakzJiwD40xxNTSVrMgxPYKYJGZz2fShuD2U2F/UaXla87IJsjzwXyG/ew7dcjrEZnYkGjd2fZtl+XELLaltEMgkXbufCza78HbxjPJzOTv9j+auEv5jJfumtsIkGxiQ2OlOq6nHdJX9b7IcWH2s9Raie3o/+QtlJf+6adc+VVSf8dVg6Mhap5A4SyRvXpt4CEgstX/CnC9bZXq5MSSltULmKGiqIQhVSKJEYVzl/RtcNtjnf9DVmoSoU7uqXKgC+gQmJ0Ny8AFgW2vEeU/+KpBmGMpklRgugJjG/PnDM0oBwFQA5kfgoG3kbdWiUgtXHV4qqVx2MD/drfLgug/QzX7kE6n9UY7r7+wsoe0qpUaw2SVLrohCYHfd2R7jFoBrpwI21whreXyUiEson+8slXcOuA5s2jotMGuc8q4it+XvFTaBpBL6m+Nwcr//elxi5IuiJxkUESeaL5sKbq2rq9jDUnYFHgdrE2CLiNCOUdhUsxkA+5yk5AkwWcP+poUTBaLWBkYMCOSJaDohfxzErZoICnP6JFZJNJ/lWcoLR/TLr9f5ay1URQQ/y/CxzqIWcfd2wRYm1RpUeVg2vpdM094TKWlgCpK9Agnj4JpZ3lXEEsm+QmA5JyFCwo/NbPH3ExWvIw=
env:
- BUILD_CONFIGURATION=Debug
- BUILD_CONFIGURATION=Release
git:
  depth: 3
language: cpp
os: windows
script:
- VisualStudio/adanaxis-win64deps/build_travis.bat
